### ISSUE TITLE
建議：醫療機構的容納量翻一番

### ISSUE THREAD

**Issue by Dynafloating** [ksp-amosa/Frostpunk_CHT#1]
### 6558
原文整句： 醫療機構的容納量翻一番。
建議校正： 醫療機構的容納量增加一倍。

---
### 6557
原文整句： 醫療機構的容量翻一番
建議校正： 醫療機構的容量增加一倍

**Comment by ksp-amosa** [comment]
程式統一取代
翻一番 -> 增加一倍
翻兩番 -> 增加二倍
