### ISSUE TITLE
建議：24小時工作

### ISSUE THREAD

**Issue by Dynafloating** [ksp-amosa/Frostpunk_CHT#4]
### 1667
原文整句：這個人24小時裡不會工作。</n>不滿值將微微增加。
建議校正：這個人在接下來的24小時將不會工作。</n>不滿值將微微增加。

### 1690, 1695
原文整句：這孩子24小時不用工作。希望將微微增加。
建議校正：這孩子在接下來的24小時將不用工作。希望將微微增加。

### 1984
原文整句：這位工程師不可能24小時在崗
建議校正：這位工程師在接下來的24小時將離開崗位

### 9286
原文：Twenty-four hours on the job? Insane. But that's our lot…
原文整句：持續工作24小時？瘋了吧？但命運如此……
建議校正：持續工作24小時？瘋了！但這是我們的命……

**Comment by ksp-amosa** [comment]
fixed
