### ISSUE TITLE
建議：蒸汽中心&蒸汽核心 -> 蒸汽樞紐

### ISSUE THREAD

**Issue by Dynafloating** [ksp-amosa/Frostpunk_CHT#5]
### 1971
原文整句：長官，一個機器人停止工作了，因為它無法在能量塔或蒸汽中心再充能。它每天需要充能兩次。為了讓它再次工作，你需要打開能量塔。
建議校正：長官，一個機器人停止工作了，因為它無法在能量塔或蒸汽樞紐再充能。它每天需要充能兩次。為了讓它再次工作，你需要打開能量塔。

### 5908
原文整句：|#color=FFD000|機器人|#defaultcolor| 能夠取代大多數工作場所的所有勞動力。 |#color=FFD000|工廠|#defaultcolor| 生產出機器人，它們每天工作24小時。它們初期的效率僅為60%，但是能夠通過研究升級提高。機器人每天兩次從能量塔或蒸汽核心再充能， 並不會影響到工作。
建議校正：|#color=FFD000|機器人|#defaultcolor| 能夠取代大多數工作場所的所有勞動力。 |#color=FFD000|工廠|#defaultcolor| 生產出機器人，它們每天工作24小時。它們初期的效率僅為60%，但是能夠通過研究升級提高。機器人每天兩次從能量塔或蒸汽樞紐再充能， 並不會影響到工作。

**Comment by ksp-amosa** [comment]
fixed
