### ISSUE TITLE
建議：設置(部分) -> 設定, 菜單 -> 選單

### ISSUE THREAD

**Issue by Dynafloating** [ksp-amosa/Frostpunk_CHT#6]
### 5954, 10083
原文整句：恢復默認設置
建議校正：恢復預設設定

### 6442
原文整句：界面/菜單/設置/人數
建議校正：界面/選單/設定/人數

### 10110
原文整句：設置
建議校正：設定

### 10462
原文整句：你總能在設置中跳過教程
建議校正：你總能在設定中跳過教程

### 5949, 8221, 9994, 10984
菜單 -> 選單

**Comment by ksp-amosa** [comment]
fixed
