### ISSUE TITLE
建議：干(部分) -> 幹 + 相關用語調整

### ISSUE THREAD

**Issue by Dynafloating** [ksp-amosa/Frostpunk_CHT#8]
### 2078
原文整句：長官，一群截肢者要見您。他們想要在伙房幫忙。</n></n>「我們不想整天坐著，滿足於活著就好。我們再也無法干重活了，但是如果我們使用一些簡單的木製義肢，我們就能在伙房幫忙並賺取生活費。」
建議校正：長官，一群截肢者要見您。他們想要在伙房幫忙。</n></n>「我們不想整天坐著，滿足於活著就好。_我們再也不能做粗重的工作了_，但是如果我們使用一些簡單的木製義肢，我們就能在伙房幫忙並賺取生活費。」

### 2388
原文整句：長官，有個人今天沒來上班。我們在他家中找到了他。有人把他鎖在家裡並在門上用粉筆寫著「死基佬」。</n></n>「是信仰守護者干的！他們鎖了門並告訴我不會讓我出去，除非我改變自己，」他說。「我不知道他們為什麼這麼做，我對任何人都沒有威脅。」
建議校正：長官，有個人今天沒來上班。我們在他家中找到了他。有人把他鎖在家裡並在門上用粉筆寫著「死基佬」。</n></n>「_是信仰守護者幹的_！他們鎖了門並告訴我不會讓我出去，除非我改變自己，」他說。「我不知道他們為什麼這麼做，我對任何人都沒有威脅。」

### 2872
原文整句：我們在損毀的雪地履帶車中發現了幾具屍體。有些被撕裂了，彷彿被什麼東西啃過。我們懷疑是北極熊干的。至於這裡發生了什麼，我們永遠無從確認。這個陰森的地方沒有任何值得我們搶救的有用之物。
建議校正：我們在損毀的雪地履帶車中發現了幾具屍體。有些被撕裂了，彷彿被什麼東西啃過。_我們懷疑是北極熊幹的_。至於這裡發生了什麼，我們永遠無從確認。這個陰森的地方沒有任何值得我們搶救的有用之物。

### 6788
原文整句：在這寒冷的煉獄建造城市需要犧牲。如果工人班次延時，他們可以干更多活。
建議校正：在這寒冷的煉獄建造城市需要犧牲。如果工人班次延時，_他們可以做更多工作_。

### 9366
原文整句：那些警衛憑什麼啥都不用干，只要呆在警衛站就好？
建議校正：_那些警衛憑什麼啥都不用幹_，只要呆在警衛站就好？

**Comment by ksp-amosa** [comment]
fixed
